# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            MF
tagline:          'Portfolio for Maurice'
description:      'Howdy, you've reached the static page for Mr. Maurice Foreman.'
url:              https://maudi84.github.io
baseurl:          /static_mf

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
