# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            StaticMF
tagline:          'Portfolio for Maurice'
description:      'Howdy, my name is Maurice. I am an aspiring web developer who is using this static page to show my work.'
url:              https://maudi84.github.io
baseurl:          /static_mf
indexurl:         /index.html

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
